server:
  port: 80


spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://eureka702.com:702/eureka/,http://eureka7001.com:7001/eureka/ #注册金集群
  instance:
    instance-id: order80
    perfer-ip-address: true
